Username transform rules before second factor merged
MultifactorLab/multifactor-radius-adapter pull request #43
Opened 2024-08-07 05:53 UTC by Gimemor

2024-08-07 06:49 UTC, apashkov-ext requested changes
1. Надобен рефакторинг, в коментах описал. Основной рефакторинг:
   > должно быть два класса: FirstFactorTransformUserNameMiddleware, SecondFactorTransformUserNameMiddleware.  
   > Метод ProcessUserNameTransformRules убрать в internal статический класс UserNameTransformation и назвать Transform. Класс положить туда же, где будут лежать две этих мидлвары.  
    > Зачем добавил async/await в мидлвары? Вроде, не нужны.
2. Адаптер поддерживает два режима проверки второго фактора: обычный и перед первым. Это учтено? Это отражено в тестах?

2024-08-07 06:49 UTC, apashkov-ext commented on src/MultiFactor.Radius.Adapter.Tests/AdapterConfig/ConfigurationLoadingTests.cs
> +        act.Clients.Should()
лишнее

2024-08-07 06:49 UTC, apashkov-ext commented on src/MultiFactor.Radius.Adapter.Tests/AdapterConfig/ConfigurationLoadingTests.cs
> +        act.Should().NotBeNull();
лишнее

2024-08-07 06:49 UTC, apashkov-ext commented on src/MultiFactor.Radius.Adapter.Tests/Data/UsernameTransformationRules/UsernameTransformationRuleTestCases.cs
> +                    new UsernameTransformationRuleTestCase()
круглые скобки не нужны, конструктор пустой

2024-08-07 06:49 UTC, apashkov-ext commented on src/MultiFactor.Radius.Adapter.Tests/Data/UsernameTransformationRules/UsernameTransformationRuleTestCase.cs
> +        public string Asset = "";
вместо полей сделать проперти

2024-08-07 06:49 UTC, apashkov-ext commented on src/MultiFactor.Radius.Adapter.Tests/Data/UsernameTransformationRules/UsernameTransformationRuleTestCase.cs
> +    public class UsernameTransformationRuleTestCase
internal

2024-08-07 06:49 UTC, apashkov-ext commented on src/MultiFactor.Radius.Adapter.Tests/Data/UsernameTransformationRules/UsernameTransformationRuleTestCases.cs
> +                    new UsernameTransformationRuleTestCase()
аналогично

2024-08-07 06:49 UTC, apashkov-ext commented on src/MultiFactor.Radius.Adapter.Tests/Pipeline/UserNameTransformMiddlewareTests.cs
> +                builder.UseMiddleware<AccessChallengeMiddleware>();
зачем challenge?

2024-08-07 06:49 UTC, apashkov-ext commented on src/MultiFactor.Radius.Adapter.Tests/Pipeline/UserNameTransformMiddlewareTests.cs
> +        public async Task Invoke_LegacyShouldChangeBothFactors(string asset, string from, string to)
из названия не понятно, что мы проверяем

2024-08-07 06:49 UTC, apashkov-ext commented on src/MultiFactor.Radius.Adapter.Tests/Pipeline/UserNameTransformMiddlewareTests.cs
> +            middleware = host.Service<TransformUserNameMiddleware>();
кажется, лишнее

2024-08-07 06:49 UTC, apashkov-ext commented on src/MultiFactor.Radius.Adapter.Tests/Pipeline/UserNameTransformMiddlewareTests.cs
> +            context.Configuration.UserNameTransformRules.BeforeFirstFactor.Length.Should().BeGreaterThan(0);
длина может быть 8? или 2?

2024-08-07 06:49 UTC, apashkov-ext commented on src/MultiFactor.Radius.Adapter/Infrastructure/Configuration/ClientLevel/ClientConfiguration.cs
> +    public ClientConfiguration AddUserNameTransformRule(UserNameTransformRulesElement rule, UserNameTransformRulesScope scope = UserNameTransformRulesScope.Both)
1. Почему класс переименован?  
2. Почему значение по умолчанию - первый + второй? Раньше же был только один из них. Это не поломает совместимость?

2024-08-07 06:49 UTC, apashkov-ext commented on src/MultiFactor.Radius.Adapter/Infrastructure/Configuration/ConfigurationLoading/ClientConfigurationFactory.cs
> +    private static void LoadUserNameTransformRulesSection(UserNameTransformRulesSection userNameTransformRulesSection, ClientConfiguration builder)
вернуть прежнюю сигнатуру метода

2024-08-07 06:49 UTC, apashkov-ext commented on src/MultiFactor.Radius.Adapter/Infrastructure/Configuration/Models/UserNameTransform/UserNameTransformRulesScope.cs
> +    Both = 0,
Почему по умолчанию? Это ничего не сломает?

2024-08-07 06:49 UTC, apashkov-ext commented on src/MultiFactor.Radius.Adapter/Infrastructure/Configuration/Models/UserNameTransform/UserNameTransformRulesScope.cs
> +public enum UserNameTransformRulesScope
UserNameTransformRulesScope -> UserNameTransformRuleKind

2024-08-07 06:49 UTC, apashkov-ext commented on src/MultiFactor.Radius.Adapter/Infrastructure/Configuration/Models/UserNameTransform/UserNameTransformRulesCollection.cs
> +    [Description("Attributes")]
Почему Attributes?  
Это копипаст. Атрибут нужен для отображения ошибки. Но, поскольку ты не знаешь, что это за секция (first\second), надо это убрать или продумать

2024-08-07 06:49 UTC, apashkov-ext commented on src/MultiFactor.Radius.Adapter/Infrastructure/Configuration/Models/UserNameTransform/UserNameTransformRulesCollection.cs
> +namespace MultiFactor.Radius.Adapter.Infrastructure.Configuration.Features.UserNameTransformFeature
неверный неймспейс.  
Надо: MultiFactor.Radius.Adapter.Infrastructure.Configuration.Models.UserNameTransform

2024-08-07 06:49 UTC, apashkov-ext commented on src/MultiFactor.Radius.Adapter/Infrastructure/Configuration/Models/UserNameTransform/UserNameTransformRulesElement.cs
> +namespace MultiFactor.Radius.Adapter.Infrastructure.Configuration.Models.UserNameTransformFeature;
MultiFactor.Radius.Adapter.Infrastructure.Configuration.Models.UserNameTransform

2024-08-07 06:49 UTC, apashkov-ext commented on src/MultiFactor.Radius.Adapter/Infrastructure/Configuration/Models/UserNameTransform/UserNameTransformRules.cs
> +    public class UserNameTransformRules
Во-первых, это не та модель, которые тут лежат - для отражения конфигов. Следуя логике организации файлов адаптера, следует этот класс положить в Features (где-то рядом или выше папка уже есть).  


Во-вторых, класс спроектирован не до конца. Я могу в люой части кода изменить его содержимое, мутировать его данные.  Вместо метода AddRule лучше использовать конструктор, передавая туда IEnumerable<> эти самых рулов. И тогда, дальше по стэку вызовов, можно будет только брать содержимое класса, но не изменять его - это важно.

2024-08-07 06:49 UTC, apashkov-ext commented on src/MultiFactor.Radius.Adapter/Server/Pipeline/TransformUserName/TransformUserNameMiddleware.cs
>      public class TransformUserNameMiddleware : IRadiusMiddleware
1. должно быть два класса:  
   - FirstFactorTransformUserNameMiddleware
   - SecondFactorTransformUserNameMiddleware
 2. Метод ProcessUserNameTransformRules убрать в internal статический класс UserNameTransformation и назвать Transform. Класс положить туда же, где будут лежать две этих мидлвары.
 3. Зачем добавил async/await?

2024-08-12 14:00 UTC, Gimemor commented on src/MultiFactor.Radius.Adapter.Tests/Data/UsernameTransformationRules/UsernameTransformationRuleTestCase.cs
> +    public class UsernameTransformationRuleTestCase
c internal не работает, inconsistent accessibility, т.к тест публичный

2024-08-12 14:28 UTC, Gimemor commented on src/MultiFactor.Radius.Adapter/Infrastructure/Configuration/ClientLevel/ClientConfiguration.cs
> +    public ClientConfiguration AddUserNameTransformRule(UserNameTransformRulesElement rule, UserNameTransformRulesScope scope = UserNameTransformRulesScope.Both)
п2. Не поломает, т. к. значение по умолчанию не используется, убрал его из сигнатуры.
Нейминг вернул

2024-08-13 09:52 UTC, Gimemor commented on src/MultiFactor.Radius.Adapter/Infrastructure/Configuration/Models/UserNameTransform/UserNameTransformRulesScope.cs
> +    Both = 0,
Чтобы трансформировать одновременно и первый фактор, и второй.
```
    <UserNameTransformRules>
        <add match="user" replace="adtest" />
    </UserNameTransformRules>
```

Такое правило в старом формате трансформирует только один раз и потом это имя используется для обоих факторов

2024-08-13 10:40 UTC, apashkov-ext requested changes

2024-08-13 10:40 UTC, apashkov-ext commented on src/MultiFactor.Radius.Adapter.Tests/Data/UsernameTransformationRules/UsernameTransformationRuleTestCases.cs
> +    class UsernameTransformationRuleTestCases
public? internal? Добавить модификатор

2024-08-13 10:40 UTC, apashkov-ext commented on src/MultiFactor.Radius.Adapter/Core/UserNameTransformation.cs
> +    static class UserNameTransformation
модификатор доступа internal

2024-08-13 10:40 UTC, apashkov-ext commented on src/MultiFactor.Radius.Adapter/Core/UserNameTransformation.cs
> +        internal static string Transform(string userName, UserNameTransformRule[] rules)
public  
и разве не надо проверить юзернейм на null или пустоту? ты много гжде это вызывваешь.  
То же самое касается и массива

2024-08-13 10:40 UTC, apashkov-ext commented on src/MultiFactor.Radius.Adapter/Infrastructure/Configuration/ClientLevel/ClientConfiguration.cs
> +    public ClientConfiguration SetUserNameTransformRules(UserNameTransformRules val)
записать в проперти значение по умолчанию и добавить проверку на  null арг8умента. Значение проперти не должно быть null

2024-08-13 10:40 UTC, apashkov-ext commented on src/MultiFactor.Radius.Adapter/Infrastructure/Configuration/Models/UserNameTransform/UserNameTransformRule.cs
> +//Copyright(c) 2022 MultiFactor
почему 2022?

2024-08-23 07:42 UTC, merged